baseURL: "http://hugo-quickstart-template.netlify.com"
languageCode: "en-us"
title: "Lucilene Pedro"
theme: "netlify-basic"
menu:
  main:
    - name: "Início"
      url: "/"
      weight: 1
    - name: "Publicações"
      url: "/sobre/"
      weight: 2
    - name: "Pesquisas"
      url: "/projetos/"
      weight: 3
