baseURL: "https://lucilenepedro.netlify.app"
languageCode: "en-us"
title: "Lucilene Pedro"
theme: "PaperMod"
menu:
  main:
    - name: "Início"
      url: "/"
      weight: 1
    - name: "Publicações"
      url: "/publicacoes/"
      weight: 2
    - name: "Projetos"
      url: "/projetos/"
      weight: 3
