baseURL: "https://lucilenepedro.netlify.app"
languageCode: "pt-br"
title: "Lucilene Pedro"

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

menu:
  main:
    - name: "Início"
      url: "/"
      weight: 1
    - name: "Publicações"
      url: "/publicacoes/"
      weight: 2
    - name: "Projetos"
      url: "/projetos/"
      weight: 3
